print("=== RAG项目入门指南 ===")
print("1. 首先确保你的数据文件存在：")
print("   ls -la data/")
print("")
print("2. 查看你的向量数据库：")
print("   ls -la chroma_db/")
print("")
print("3. 尝试运行最简单的测试：")
print("   python -c \"import sys; print('Python版本:', sys.version)\"")
print("")
print("4. 如果不知道主程序，搜索：")
print("   grep -r 'FastAPI\|Flask' --include='*.py' .")
print("")
print("5. 或者创建一个最简单的测试：")
print("   创建一个 test_simple.py，包含上面给的简单RAG示例")
